# Form implementation generated from reading ui file 'bank_gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 800)
        MainWindow.setMinimumSize(QtCore.QSize(530, 800))
        MainWindow.setMaximumSize(QtCore.QSize(530, 800))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_main = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_main.setGeometry(QtCore.QRect(0, 0, 531, 751))
        self.frame_main.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_main.setObjectName("frame_main")
        self.Frame_checking = QtWidgets.QFrame(parent=self.frame_main)
        self.Frame_checking.setGeometry(QtCore.QRect(0, 120, 531, 181))
        self.Frame_checking.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Frame_checking.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Frame_checking.setObjectName("Frame_checking")
        self.label_welcome_user_2 = QtWidgets.QLabel(parent=self.Frame_checking)
        self.label_welcome_user_2.setGeometry(QtCore.QRect(20, 10, 261, 51))
        self.label_welcome_user_2.setObjectName("label_welcome_user_2")
        self.textBrowser_checking_amount = QtWidgets.QTextBrowser(parent=self.Frame_checking)
        self.textBrowser_checking_amount.setGeometry(QtCore.QRect(20, 80, 211, 41))
        self.textBrowser_checking_amount.setObjectName("textBrowser_checking_amount")
        self.pushButton_checking_deposite = QtWidgets.QPushButton(parent=self.Frame_checking)
        self.pushButton_checking_deposite.setGeometry(QtCore.QRect(370, 20, 141, 61))
        self.pushButton_checking_deposite.setObjectName("pushButton_checking_deposite")
        self.pushButton_checking_withdrawl = QtWidgets.QPushButton(parent=self.Frame_checking)
        self.pushButton_checking_withdrawl.setGeometry(QtCore.QRect(370, 100, 141, 61))
        self.pushButton_checking_withdrawl.setObjectName("pushButton_checking_withdrawl")
        self.frame_user_info = QtWidgets.QFrame(parent=self.frame_main)
        self.frame_user_info.setGeometry(QtCore.QRect(0, 0, 531, 121))
        self.frame_user_info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_user_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_user_info.setObjectName("frame_user_info")
        self.label_welcome_user = QtWidgets.QLabel(parent=self.frame_user_info)
        self.label_welcome_user.setGeometry(QtCore.QRect(10, 20, 501, 71))
        self.label_welcome_user.setObjectName("label_welcome_user")
        self.Frame_saving = QtWidgets.QFrame(parent=self.frame_main)
        self.Frame_saving.setGeometry(QtCore.QRect(0, 300, 531, 191))
        self.Frame_saving.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Frame_saving.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Frame_saving.setObjectName("Frame_saving")
        self.textBrowser_saving_amount = QtWidgets.QTextBrowser(parent=self.Frame_saving)
        self.textBrowser_saving_amount.setGeometry(QtCore.QRect(20, 80, 211, 41))
        self.textBrowser_saving_amount.setObjectName("textBrowser_saving_amount")
        self.label_welcome_user_3 = QtWidgets.QLabel(parent=self.Frame_saving)
        self.label_welcome_user_3.setGeometry(QtCore.QRect(20, 10, 221, 51))
        self.label_welcome_user_3.setObjectName("label_welcome_user_3")
        self.pushButton_saving_deposite = QtWidgets.QPushButton(parent=self.Frame_saving)
        self.pushButton_saving_deposite.setGeometry(QtCore.QRect(370, 20, 141, 61))
        self.pushButton_saving_deposite.setObjectName("pushButton_saving_deposite")
        self.pushButton_saving_withdrawl = QtWidgets.QPushButton(parent=self.Frame_saving)
        self.pushButton_saving_withdrawl.setGeometry(QtCore.QRect(370, 100, 141, 61))
        self.pushButton_saving_withdrawl.setObjectName("pushButton_saving_withdrawl")
        self.frame_history = QtWidgets.QFrame(parent=self.frame_main)
        self.frame_history.setGeometry(QtCore.QRect(0, 490, 531, 261))
        self.frame_history.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_history.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_history.setObjectName("frame_history")
        self.textBrowser_saving_history = QtWidgets.QTextBrowser(parent=self.frame_history)
        self.textBrowser_saving_history.setGeometry(QtCore.QRect(270, 60, 251, 192))
        self.textBrowser_saving_history.setObjectName("textBrowser_saving_history")
        self.textBrowser_checking_history = QtWidgets.QTextBrowser(parent=self.frame_history)
        self.textBrowser_checking_history.setGeometry(QtCore.QRect(10, 60, 251, 192))
        self.textBrowser_checking_history.setObjectName("textBrowser_checking_history")
        self.label_welcome_user_4 = QtWidgets.QLabel(parent=self.frame_history)
        self.label_welcome_user_4.setGeometry(QtCore.QRect(10, 10, 221, 31))
        self.label_welcome_user_4.setObjectName("label_welcome_user_4")
        self.label_welcome_user_5 = QtWidgets.QLabel(parent=self.frame_history)
        self.label_welcome_user_5.setGeometry(QtCore.QRect(270, 10, 201, 31))
        self.label_welcome_user_5.setObjectName("label_welcome_user_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_welcome_user_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">Checking Account</span></p><p><br/></p></body></html>"))
        self.textBrowser_checking_amount.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">$0.0</span></p></body></html>"))
        self.pushButton_checking_deposite.setText(_translate("MainWindow", "Deposite"))
        self.pushButton_checking_withdrawl.setText(_translate("MainWindow", "Withdrawl"))
        self.label_welcome_user.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">Welcome User</span></p></body></html>"))
        self.textBrowser_saving_amount.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">$100.0</span></p></body></html>"))
        self.label_welcome_user_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">Saving Account</span></p><p><br/></p></body></html>"))
        self.pushButton_saving_deposite.setText(_translate("MainWindow", "Deposite"))
        self.pushButton_saving_withdrawl.setText(_translate("MainWindow", "Withdrawl"))
        self.textBrowser_saving_history.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_checking_history.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_welcome_user_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Checking Transactions </span></p><p><span style=\" font-size:16pt;\"><br/></span></p></body></html>"))
        self.label_welcome_user_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Saving Transactions</span></p><p><span style=\" font-size:16pt;\"><br/></span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
